### ISSUE TITLE
Cannot find module '~/dev/DMF/impact-admin/bower_components/ember/ember-template-compiler.js'

### ISSUE THREAD

**Issue by maladon** [esbanarango/ember-credit-card#10]
ember 2.11
ember-credit-card 2.2.0

after installing and running the generator I get this error running an ember build:

```
Hubert:impact-admin maladon$ ember build
⠋ BuildingCannot find module '/Users/maladon/dev/DMF/impact-admin/bower_components/ember/ember-template-compiler.js'
Error: Cannot find module '/Users/maladon/dev/DMF/impact-admin/bower_components/ember/ember-template-compiler.js'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Class.htmlbarsOptions (/Users/maladon/dev/DMF/impact-admin/node_modules/ember-credit-card/node_modules/ember-cli-htmlbars/ember-addon-main.js:88:25)
    at Object.toTree (/Users/maladon/dev/DMF/impact-admin/node_modules/ember-credit-card/node_modules/ember-cli-htmlbars/ember-addon-main.js:31:43)
    at /Users/maladon/dev/DMF/impact-admin/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/Users/maladon/dev/DMF/impact-admin/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at module.exports.preprocessTemplates (/Users/maladon/dev/DMF/impact-admin/node_modules/ember-cli-preprocess-registry/preprocessors.js:161:10)
```

**Comment by maladon** [comment]
I just did a test of a clean ember project. in a new directory I did `ember init`, then installed this plugin and ran `ember build`. Got the same error as above.

**Comment by mjhlobdell** [comment]
👍
