### ISSUE TITLE
Cannot find module 'handlebars'

### ISSUE THREAD

**Issue by muhang** [esbanarango/ember-credit-card#2]
After installing the npm package and running the generator, I can no longer start the ember app, getting the message:
```
Cannot find module 'handlebars'
Error: Cannot find module 'handlebars'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at /Users/muhanguclu/Dev/github/dashboard-ember/bower_components/ember/ember-template-compiler.js:34:16
    at Object.<anonymous> (/Users/muhanguclu/Dev/github/dashboard-ember/bower_components/ember/ember-template-compiler.js:295:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
```
I chased this around for a little while, and tried re-installing node_modules and running `bower install handlebars` , but nothing seems to work.

Ember -v Output:
```
version: 0.2.0
http_parser: 2.3
node: 0.12.4
v8: 3.28.71.19
uv: 1.5.0
zlib: 1.2.8
modules: 14
openssl: 1.0.1m
npm: 2.7.0
```

**Comment by esbanarango** [comment]
@muhang Can you paste your `package.json` here pls.

**Comment by muhang** [comment]
Sure thing: 
```
{
  "name": "dashboard",
  "version": "0.0.0",
  "private": true,
  "directories": {
    "doc": "doc",
    "test": "tests"
  },
  "scripts": {
    "start": "ember server",
    "build": "ember build",
    "test": "ember test"
  },
  "repository": "",
  "engines": {
    "node": ">= 0.10.0"
  },
  "author": "Muhan Guclu",
  "license": "MIT",
  "devDependencies": {
    "broccoli-asset-rev": "^1.0.0",
    "broccoli-merge-trees": "^0.1.4",
    "broccoli-sass": "^0.2.0",
    "broccoli-static-compiler": "^0.1.4",
    "broccoli-svgmerge": "git://github.com/danstever/broccoli-svgmerge.git",
    "connect-restreamer": "^1.0.1",
    "ember-cli": "0.2.0",
    "ember-cli-6to5": "0.2.1",
    "ember-cli-chart": "^1.0.6",
    "ember-cli-compass-bootstrap": "0.0.5",
    "ember-cli-content-security-policy": "0.3.0",
    "ember-cli-datepicker": "^1.3.2",
    "ember-cli-dependency-checker": "0.0.6",
    "ember-cli-htmlbars": "^0.6.0",
    "ember-cli-ic-ajax": "0.1.1",
    "ember-cli-inject-live-reload": "^1.3.0",
    "ember-cli-qunit": "0.3.9",
    "ember-cli-simple-auth": "0.7.3",
    "ember-cli-simple-auth-testing": "0.7.3",
    "ember-cli-uglify": "^1.0.1",
    "ember-credit-card": "^1.0.0",
    "ember-data": "1.0.0-beta.12",
    "ember-export-application-global": "^1.0.0",
    "ember-localstorage-adapter": "^0.5.0",
    "ember-radio-buttons": "^3.0.0",
    "express": "^4.8.5",
    "glob": "^4.0.5",
    "mocha-jshint": "^1.0.0",
    "morgan": "^1.5.1"
  },
  "dependencies": {
    "ember-cli-sentry": "^1.0.3",
    "ember-radio-buttons": "^3.0.1",
    "rimraf": "2.2.8"
  }
}
```

**Comment by esbanarango** [comment]
@muhang Could you trying doing this:

`npm install handlebars --save-dev`

**Comment by esbanarango** [comment]
@muhang were you able to make this work?

**Comment by muhang** [comment]
I wasn't, but I didn't have enough time to exhaust all options (needed to set it up rather quickly for a release) and ended up just using jquery payments, since my use case didn't require the full Card UI. I did try running `npm install handlebars --save-dev` though, which didn't work. I can't speak to the current state of the issue though.

**Comment by esbanarango** [comment]
I'll close this issue. And I'll investigate it locally.
